on:
  push:
    branches:
      - master
    
jobs:
  build-and-deploy:
    name: Build and Deploy to Azure
    runs-on: ubuntu-latest
    steps:
      # checkout action unu kullan
      - uses: actions/checkout@master
      # nodejs kurma
      - name: Install NodeJS 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      # npm install build ve test
      - name: npm install&build&test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      # azure deployment
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v1
        with: 
          app-name: azureweathermlsa
          package: '.'
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}

